import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { Command } from 'commander';
import { output } from '../ui/output.js';

interface ContractArtifact {
  abi: unknown[];
  bytecode?: { object: string };
  deployedBytecode?: { object: string };
  methodIdentifiers?: Record<string, string>;
}

interface ExtractedAbi {
  name: string;
  abi: unknown[];
  path: string;
}

/**
 * Find Foundry out directory
 */
async function findFoundryOut(targetDir: string): Promise<string | null> {
  const candidates = [
    join(targetDir, 'out'),
    join(targetDir, 'artifacts'),
    join(targetDir, 'build'),
  ];

  for (const candidate of candidates) {
    try {
      await access(candidate);
      return candidate;
    } catch {
      // Continue to next candidate
    }
  }

  return null;
}

/**
 * Recursively find all JSON artifacts in a directory
 */
async function findArtifacts(dir: string): Promise<string[]> {
  const artifacts: string[] = [];

  async function walk(currentDir: string): Promise<void> {
    const entries = await readdir(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = join(currentDir, entry.name);

      if (entry.isDirectory()) {
        await walk(fullPath);
      } else if (entry.name.endsWith('.json') && !entry.name.includes('.dbg.')) {
        artifacts.push(fullPath);
      }
    }
  }

  await walk(dir);
  return artifacts;
}

/**
 * Extract ABI from a Foundry artifact
 */
async function extractAbi(artifactPath: string): Promise<ExtractedAbi | null> {
  try {
    const content = await readFile(artifactPath, 'utf-8');
    const artifact = JSON.parse(content) as ContractArtifact;

    if (!artifact.abi || artifact.abi.length === 0) {
      return null;
    }

    // Get contract name from path (e.g., out/MyContract.sol/MyContract.json)
    const fileName = basename(artifactPath, '.json');

    return {
      name: fileName,
      abi: artifact.abi,
      path: artifactPath,
    };
  } catch {
    return null;
  }
}

/**
 * Generate TypeScript types for ABI (basic version)
 */
function generateTypes(abi: ExtractedAbi): string {
  const lines: string[] = [
    '// Generated by AgentForge - DO NOT EDIT',
    `// Source: ${abi.path}`,
    '',
    `export const ${abi.name}Abi = ${JSON.stringify(abi.abi, null, 2)} as const;`,
    '',
    `export type ${abi.name}Abi = typeof ${abi.name}Abi;`,
    '',
  ];

  return lines.join('\n');
}

/**
 * Generate index file for all ABIs
 */
function generateIndex(abis: ExtractedAbi[]): string {
  const exports = abis.map((abi) => `export * from './${abi.name}.js';`);
  return ['// Generated by AgentForge - DO NOT EDIT', '', ...exports, ''].join('\n');
}

/**
 * Create the types command
 */
export function createTypesCommand(): Command {
  return new Command('types')
    .description('Extract ABIs from Foundry artifacts and generate TypeScript types')
    .option('-d, --dir <path>', 'Target directory with Foundry project', '.')
    .option('-o, --out <path>', 'Output directory for generated types', 'sim/generated/abi')
    .option('--no-index', 'Do not generate index.ts file')
    .option('-f, --filter <pattern>', 'Filter contracts by name pattern')
    .option('--json', 'Output result as JSON')
    .action(async (options) => {
      const targetDir = options.dir;
      const outDir = join(targetDir, options.out);
      const jsonOutput = options.json;

      if (!jsonOutput) {
        output.header('AgentForge Types Generator');
        output.info('Searching for Foundry artifacts...');
      }

      // Find Foundry out directory
      const foundryOut = await findFoundryOut(targetDir);
      if (!foundryOut) {
        if (jsonOutput) {
          console.log(JSON.stringify({ success: false, error: 'Foundry out directory not found' }));
        } else {
          output.error('Foundry out directory not found');
          output.info('Run "forge build" first to compile your contracts');
        }
        process.exit(1);
      }

      if (!jsonOutput) {
        output.success(`Found Foundry artifacts at: ${foundryOut}`);
      }

      // Find all artifacts
      const artifactPaths = await findArtifacts(foundryOut);
      if (artifactPaths.length === 0) {
        if (jsonOutput) {
          console.log(JSON.stringify({ success: false, error: 'No artifacts found' }));
        } else {
          output.error('No artifacts found');
        }
        process.exit(1);
      }

      // Extract ABIs
      const abis: ExtractedAbi[] = [];
      for (const path of artifactPaths) {
        const abi = await extractAbi(path);
        if (abi) {
          // Apply filter if specified
          if (options.filter) {
            const pattern = new RegExp(options.filter, 'i');
            if (!pattern.test(abi.name)) {
              continue;
            }
          }
          abis.push(abi);
        }
      }

      if (abis.length === 0) {
        if (jsonOutput) {
          console.log(JSON.stringify({ success: false, error: 'No ABIs extracted' }));
        } else {
          output.error('No ABIs extracted (contracts may not have ABIs)');
        }
        process.exit(1);
      }

      if (!jsonOutput) {
        output.info(`Found ${abis.length} contracts with ABIs`);
      }

      // Create output directory
      await mkdir(outDir, { recursive: true });

      // Generate type files
      const generated: string[] = [];
      for (const abi of abis) {
        const typeContent = generateTypes(abi);
        const typePath = join(outDir, `${abi.name}.ts`);
        await writeFile(typePath, typeContent);
        generated.push(abi.name);

        if (!jsonOutput) {
          output.success(`Generated: ${abi.name}.ts`);
        }
      }

      // Generate index file
      if (options.index !== false) {
        const indexContent = generateIndex(abis);
        const indexPath = join(outDir, 'index.ts');
        await writeFile(indexPath, indexContent);

        if (!jsonOutput) {
          output.success('Generated: index.ts');
        }
      }

      if (jsonOutput) {
        console.log(
          JSON.stringify({
            success: true,
            outputDir: outDir,
            contracts: generated,
            count: generated.length,
          })
        );
      } else {
        output.newline();
        output.success(`Generated ${generated.length} type files in ${outDir}`);
        output.info('Import ABIs using:');
        output.info(`  import { MyContractAbi } from '${options.out}/index.js'`);
      }
    });
}
